


--Tabela usuario
create table USUARIO
	(
		ID INT IDENTITY,
		LOGIN VARCHAR(30) NOT NULL,
		SENHA VARCHAR(30) NOT NULL,
		DT_EXPIRACAO DATE NOT NULL CONSTRAINT DF_DT_EXPIRACAO DEFAULT ('01/01/1900'), 

		CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
		CONSTRAINT UQ_LOGIN UNIQUE( LOGIN ),
		
	);

--tabela curso
CREATE TABLE CURSO 
(
	ID		INT IDENTITY ,
	NOME	VARCHAR (50) NOT NULL,

	CONSTRAINT PK_CURSO PRIMARY KEY (ID),
	CONSTRAINT UQ_CURSO_NOME UNIQUE (NOME)
);

--Tabela coordenador
	create table COORDENADOR
	(
		ID INT IDENTITY ,
		ID_USUARIO INT NOT NULL,
		NOME VARCHAR (50) NOT NULL,
		EMAIL VARCHAR(40) NOT NULL,
		CELULAR CHAR (14) NOT NULL,

		CONSTRAINT PK_COORDENADOR PRIMARY KEY( ID ),
		CONSTRAINT UQ_EMAIL UNIQUE(EMAIL),
		CONSTRAINT UQ_CELULAR UNIQUE(CELULAR),
		CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) 
			REFERENCES USUARIO (ID),
	);

--Tabela professor
	create table PROFESSOR
	(
		ID INT IDENTITY ,
		ID_USUARIO INT NOT NULL,
		EMAIL_PROFESSOR VARCHAR(40) NOT NULL,
		CELULAR_PROFESSOR CHAR (14)NOT NULL, 
		APELIDO VARCHAR(50)NOT NULL,

		CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID),
		CONSTRAINT UQ_EMAIL_PROFESSOR UNIQUE(EMAIL_PROFESSOR),
		CONSTRAINT UQ_CELULAR_PROFESSOR UNIQUE(CELULAR_PROFESSOR),
		CONSTRAINT FK_PROFESSOR_ID_USUARIO FOREIGN KEY (ID_USUARIO) 
			REFERENCES USUARIO (ID),
	);

--Tabela aluno
	create table ALUNO
	(
		ID INT IDENTITY ,
		ID_USUARIO INT NOT NULL,
		NOME VARCHAR (50) NOT NULL,
		EMAIL_ALUNO VARCHAR(40) NOT NULL,
		CELULAR_ALUNO CHAR (14) NOT NULL,
		RA CHAR(10) NOT NULL,
		FOTO VARCHAR(100)

		CONSTRAINT PK_ALUNO PRIMARY KEY( ID ),
		CONSTRAINT UQ_EMAIL_ALUNO UNIQUE(EMAIL_ALUNO),
		CONSTRAINT UQ_CELULAR_ALUNO UNIQUE(CELULAR_ALUNO),
		CONSTRAINT FK_ALUNO_ID_USUARIO FOREIGN KEY (ID_USUARIO) 
			REFERENCES USUARIO (ID)
	);

