


--Tabela usuario
create table USUARIO
	(
		ID INT IDENTITY,
		LOGIN VARCHAR(30) NOT NULL,
		SENHA VARCHAR(30) NOT NULL,
		DT_EXPIRACAO DATE NOT NULL CONSTRAINT DF_DT_EXPIRACAO DEFAULT ('01/01/1900'), 

		CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
		CONSTRAINT UQ_LOGIN UNIQUE( LOGIN ),
		
	);

--tabela curso
CREATE TABLE CURSO 
(
	ID		INT IDENTITY ,
	NOME	VARCHAR (50) NOT NULL,

	CONSTRAINT PK_CURSO PRIMARY KEY (ID),
	CONSTRAINT UQ_CURSO_NOME UNIQUE (NOME)
);

--Tabela coordenador
	create table COORDENADOR
	(
		ID INT IDENTITY ,
		ID_USUARIO INT NOT NULL,
		NOME VARCHAR (50) NOT NULL,
		EMAIL VARCHAR(40) NOT NULL,
		CELULAR CHAR (14) NOT NULL,

		CONSTRAINT PK_COORDENADOR PRIMARY KEY( ID ),
		CONSTRAINT UQ_EMAIL UNIQUE(EMAIL),
		CONSTRAINT UQ_CELULAR UNIQUE(CELULAR),
		CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) 
			REFERENCES USUARIO (ID),
	);

